require.config({
    paths: {
        'TourModel': Lizard.appBaseUrl + 'webresource/tour/models/tourModel',
        'TourStore': Lizard.appBaseUrl + 'webresource/tour/models/tourStore',
        'VaBaseView': Lizard.appBaseUrl + 'webresource/tour/res/scripts/views/BaseView',
        'Timer': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/Timer',
        'Util': Lizard.appBaseUrl + 'webresource/tour/res/scripts/util',
        'ImageSlider': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/c.ui.imageSlider',
        'Cities': Lizard.appBaseUrl + 'webresource/tour/res/data/cities',
        'IScroll': Lizard.appBaseUrl + 'webresource/tour/res/data/iscroll',
		'Destcities': Lizard.appBaseUrl + 'webresource/tour/res/data/destcities',
		'BookingBaseView': Lizard.appBaseUrl + 'webresource/tour/controllers/BookingBaseView',
		'Calendar2': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/Calendar2',
		'NumberPicker': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/NumberPicker',
		'inherit': Lizard.appBaseUrl + 'webresource/tour/res/libs/inherit',
		'EventEmitter': Lizard.appBaseUrl + 'webresource/tour/res/libs/EventEmitter',
		'DateChinese': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/DateChinese',
		'FakeDetail': Lizard.appBaseUrl + 'webresource/tour/templates/fakeDetail.html',
		'VacationCity': Lizard.appBaseUrl + 'webresource/tour/templates/vacationcity.html',
		'DepartSearch': Lizard.appBaseUrl + 'webresource/tour/templates/departsearch.html',
        'Question': Lizard.appBaseUrl + 'webresource/tour/templates/question.html',
        'DetailVisa': Lizard.appBaseUrl + 'webresource/tour/templates/detail.visa.html',
        'DetailBookingNote': Lizard.appBaseUrl + 'webresource/tour/templates/detail.booking.note.html',
        'Destination': Lizard.appBaseUrl + 'webresource/tour/templates/destination.html',
        'BookingStep1': Lizard.appBaseUrl + 'webresource/tour/templates/booking.step1.html',
        'WidgetPriceDetail': Lizard.appBaseUrl + 'webresource/tour/templates/widget.price.detail.html',
        'Calendar2Day': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/Calendar2-day.html',
        'Calendar2Frame': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/Calendar2-frame.html',
        'Calendar2Month': Lizard.appBaseUrl + 'webresource/tour/res/scripts/widget/Calendar2-month.html',
        'VacationListController': Lizard.appBaseUrl + "webresource/tour/controllers/vacationlist"
    }
});